export const expenseCategories = [
  'Food',
  'Clothing',
  'Transportation',
  'Entertainment',
  'Health',
  'Housing',
  'Utilities',
  'Insurance',
  'Education',
  'Travel',
  'Personal Care',
  'Groceries',
  'Dining Out',
  'Subscriptions',
  'Home Maintenance',
  'Childcare',
  'Gifts',
  'Hobbies',
  'Pet Care',
  'Miscellaneous',
]

export const incomeCategories = [
  'Salary',
  'Bonus',
  'Freelance Work',
  'Side Income',
  'Investment Earnings',
  'Rental Earnings',
  'Gifts Received',
  'Tax Refunds',
  'Pension Payments',
  'Interest Earnings',
  'Dividend Payments',
  'Sales Income',
  'Commissions Earned',
  'Royalties Received',
  'Scholarships Awarded',
  'Cash Awards',
  'Grants Received',
  'Miscellaneous Income',
]
